version: '3'

services:
  api:
    build: .
    command: "flask run -h 0.0.0.0 -p8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
